name: namecheap-ddns-client
base: core18
version: '0.1'
summary: Dynamic-DNS client for Namecheap
description: |
  Small and uncomplicated snap to use Namecheap dynamic DNS services.
  You just need to configure three attributes:
      $ snap set namecheap-ddns-client password=${PASSWORD}
      $ snap set namecheap-ddns-client domain=${FQDN}
      $ snap set namecheap-ddns-client host=${HOST}

  You can also do this in one step as shown in the example below:

      $ snap set namecheap-ddns-client domain=example.com host=@ password=mypassword

  If everything is setup correctly, you can see that every five minutes,
  the IP address is updated. In case of any complications, just checkout the logs:

      $ sudo journalctl -fu snap.namecheap-ddns-client.ncddns

grade: stable
confinement: strict
icon: snap/logo/ncddns.svg

apps:
  ncddns:
    command: bin/ncddns
    daemon: simple
    plugs: [network]

parts:
  ncddns:
    plugin: dump
    source: ./bin
    organize:
      ncddns: bin/
    stage-packages: [curl, libxml2-utils]
